spring:
  datasource:
    url: jdbc:mysql://localhost:2333/ana_system?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: FTY19132

mybatis:
  configuration:
    map-underscore-to-camel-case: true